version: '3'

services:
  db:
    image: docker.io/mariadb:10.7
    container_name: slapbot_db
    restart: on-failure:3
    ports:
      - '127.0.0.1:3306:3306'
    env_file: env/app-dev.env
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: docker.io/phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: on-failure:3
    ports:
      - '127.0.0.1:8081:80'
    environment:
      PMA_HOST: db
